### PR TITLE
Verify that the Let's encrypt setup works

### PR DESCRIPTION
**Pull request by ivan-stankov-golang**

### CODE REVIEW

**Comment by ceckoslab** [comment]
@ivan-stankov-golang I see that we remove part of the tests around Let's Encrypt. 

Another time, alternatively we can have a different independent testing where we spin an environment for an integration subdomain and we then run few checks about let's encrypt and other stuff.

**Comment by ivan-stankov-golang** [comment]
> @ivan-stankov-golang I see that we remove part of the tests around Let's Encrypt.
> 
> Another time, alternatively we can have a different independent testing where we spin an environment for an integration subdomain and we then run few checks about let's encrypt and other stuff.

The Let's Encrypt test changes broke the production code for Let's Encrypt and needed to be removed.

**Comment by ceckoslab** [comment]
@ivan-stankov-golang I am ready accept the pull request but for the benefit of the doubt, do you think that we can explore alternative fix where we keep the delete integration tests?

I am really interested to know if we can understand the root cause.

**Comment by ivan-stankov-golang** [comment]
opened new PR: https://github.com/basicrum/front_basicrum_go/pull/91

**Pull request closed without merging**
