### PR TITLE
Dockerize and push to Docker hub

### PR DESCRIPTION
**Pull request by ivan-stankov-golang**

### CODE REVIEW

**Comment by ceckoslab** [comment]
Hello @ivan-stankov-golang ,

Could we do 2 additions to this PR:

1. Could we add the produced Docker image to be used for running a container that will be used all the GitHub actions and tests?
2. Could we add a version parameter for the **docker-hub** command? The current implementation will always push to the latest but I also would like to bump a specific version. This will be very helpful when I creating a docker-compose file that runs **front_basicrum_go** together with Grafana and ClickHouse.

**Comment by ivan-stankov-golang** [comment]
for point 2: Example: VERSION=1 make docker-hub

**Comment by ivan-stankov-golang** [comment]
for point 1 - I will check what needs to be changed

**Comment by ivan-stankov-golang** [comment]
check point 1.

**Review by ceckoslab — APPROVED** [review]
LGTM

**Pull request merged**
